package com.ministerio.starparking.common.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGED,

    PROFILE_UPDATED,
    ACCOUNT_DELETED,

    VEHICLE_ADDED,
    VEHICLE_UPDATED,
    VEHICLE_REMOVED,

    PARKING_STARTED,
    PARKING_ENDED,
    PARKING_EXTENDED,

    PARKING_SPOT_RESERVED,
    PARKING_SPOT_CANCELLED,

    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELLED,

    PAYMENT_CREATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    BILL_GENERATED
}
